language: objective-c
osx_image: xcode9

script:
  - set -o pipefail
  - xcodebuild build test -scheme Constrainer -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0' | xcpretty
  - bash <(curl -s https://codecov.io/bash)
